Refactor internal `PaginatedResult` API to have non-optional methods
This changes condition based function properties in the internal
`PaginatedResult` to regular class methods.

The spec TG5 [1] does not specify if the link to the first page (or
current) can be missing in the response and what should be done in such
case, so the new implementation is the best effort attempt to bring the
internal `PaginatedResult` API in line with the public API, while
keeping the same function behavior as before.

The new implementation will result in an thrown error if there was no
link to the first or current page, just like it would before since those
methods would not exist on the class. Essentially this changes only the
type of the error thrown: for example, instead of
"TypeError: page.current is not a function" the client will get
"Error: Missing link to the current page of results".

Users of the client library should not have expected the .first() and
.current() methods to be optional before, as the public definition
for `PaginatedResult` in ably.d.ts declares them as regular methods,
thus this should not be a breaking change.

This makes internal `PaginatedResult` match the public one in ably.d.ts.
This enables union types between internal and public APIs for
`PaginatedResult`, which will be needed for new Push device
listSubscriptions API in [2].

[1] https://sdk.ably.com/builds/ably/specification/main/features/#TG5
[2] https://github.com/ably/ably-js/pull/2013