Add import of Transport in platform.ts
This starts to fail as of TypeScript 4.3.5:

>  ERROR in /Users/lawrence/code/ably/ably-js/src/common/platform.ts
>  ./src/common/platform.ts 13:76-85
>  [tsl] ERROR in /Users/lawrence/code/ably/ably-js/src/common/platform.ts(13,77)
>        TS2304: Cannot find name 'Transport'.

Not sure why it’s working in our current TypeScript version. Seems like
an uncontroversial change, though.