Configure ruby tool version to match what's expected by the internal repository.
If I don't tell ASDF that I want the older Ruby then I get:

Running "release:ably-deploy" task
Publishing version 1.1.25 of the library to the CDN
>> Executing BUNDLE_GEMFILE="../infrastructure/Gemfile" bundle exec ../infrastructure/bin/ably-env deploy javascript --version 1.1.25
Fatal error: Error executing "BUNDLE_GEMFILE="../infrastructure/Gemfile" bundle exec ../infrastructure/bin/ably-env deploy javascript --version 1.1.25": /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your ../infrastructure/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
	from /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
	from /Users/quintin/.asdf/installs/ruby/2.7.0/bin/bundle:23:in `<main>'